<?php
/* $Id$ */

/**
 * @file
 * Evaluate a users expertise and display the result on the user's profile page.
 * 
 * @author
 * Stefan Auditor <stefan.auditor@erdfisch.de>
 */

/**
 * Implementation of hook_user().
 */
function user_expertise_user($op, &$edit, &$account, $category = NULL) {
  global $user;

  if ($op == 'view') {
    $expertise = array(
      'nodes' => user_expertise_overall($account),
      'comments' => user_expertise_overall($account, 'comment'),
    );
    
    if ($expertise['nodes']) {
      $items['user_expertise_overall_nodes'] = array(
        'title' => t('Overall node expertise'),
        'value' => theme('user_expertise_o_meter', $expertise['nodes']),
        'class' => 'user-expertise-overall-nodes',
      );
    }
    if ($expertise['comments']) {
      $items['user_expertise_overall_comments'] = array(
        'title' => t('Overall comment expertise'),
        'value' => theme('user_expertise_o_meter', $expertise['comments']),
        'class' => 'user-expertise-overall-comments',
      );
    }
    
    return $items ? array(t('User expertise') => $items) : NULL;
  }
}

/**
 * Generate a percentage value representing a user's overall experise
 * @param user a user object
 * @param type a string describing the object type
 * @return an integer representing a percentage
 */
function user_expertise_overall($user, $type = 'node') {
  
  $expertise = db_fetch_object(db_query("SELECT AVG(vc.value) AS expertise FROM {votingapi_cache} vc
                                            INNER JOIN {node} n 
                                            WHERE n.uid = %d
                                              AND vc.content_id = n.nid
                                              AND vc.function = 'average'
                                              AND vc.content_type = '%s'
  ", $user->uid, $type));

  return $expertise->expertise ? $expertise->expertise : NULL;
}

/**
 * Display a percentage meter
 * @param index a integer value representing a percentage
 * @return a percentage meter in html
 */
function theme_user_expertise_o_meter($index) {
  if (is_numeric($index)) {
    $output = '
    <div class="user_activity_o_meter" style="width:100%;height:20px;background-color:#C3D9FF;">
      <div style="width:'. $index .'%;height:20px;background-color:#6BBA70;color:white;text-align:center;"></div>
      <div style="margin-top:-20px;text-align:center;">'. $index .'%</div>
    </div>';
  }
  else {
    $output = t('No evaluation available.');
  }
  
  return $output;
}



